### PR TITLE
Minor changes for Simplification

### PR DESCRIPTION
**Pull request by kayuksel**
- Replaced the identity module with a lambda function
- Removed a small redundant part of the forward function
- Cleaned and shortened code with some minor changes
Note: I should have preserved all of the functionality.

### CODE REVIEW

**Review by elliotjcrowley — DISMISSED** [review]
If there is a shortcut connection, x must go through the first batch-norm and ReLU beforehand.

**Comment by kayuksel** [comment]
@elliotjcrowley I have corrected it accordingly, I believe that it is as you have requested now.

**Comment by kayuksel** [comment]
Ah, sorry, I have forgot that I have removed ReLU from the Downblock, will make another fix now.

**Comment by kayuksel** [comment]
I haven't pushed the following as I haven't tested it but, that's also much nicer way implementation in my personal opinion. Latest full version of my changes are available here: https://github.com/kayuksel/pytorch-GENet/blob/master/models/blocks.py

```
        if extra_params:
            modules = []
            if extent: modules.append(Downblock(out_planes))
            if extent == 4: modules.append(nn.Sequential(nn.ReLU(inplace=True), Downblock(out_planes)))
            if extent == 8: modules.append(nn.Sequential(nn.ReLU(inplace=True), Downblock(out_planes)))
            self.downop = nn.Sequential(*modules) if extent else Downblock(out_planes, kernel_size=spatial)
        else:
            self.downop = nn.AdaptiveAvgPool2d(spatial // extent) if extent else self.downop = nn.AdaptiveAvgPool2d(1)
```

**Comment by kayuksel** [comment]
@elliotjcrowley You can even append those subsequent nn.Sequential(s) via a for-loop to support any arbitrary value of the extent without having if checks. Something similar to the following code:

```
            if extent: modules = [Downblock(out_planes)]
            for i in range(extent // 2)
                modules.append(nn.Sequential(nn.ReLU(inplace=True), Downblock(out_planes)))
```

**Comment by elliotjcrowley** [comment]
Colon missing on line 35.

The input to the shortcut only goes through BN and RELU. It's currently set up to go through BN RELU and the first conv.

**Comment by kayuksel** [comment]
@elliotjcrowley Ok, I believe that I have fixed those now. Thank you for your time and consideration.

**Comment by kayuksel** [comment]
Only issue that I can think of 
`for i in range(extent // 2):  => for i in range((extent-1) // 2):`
Anyways, thanks. Cheers.

**Pull request closed without merging**
